/* Glass Groove: the service worker. Generated by tools/build-sw.js: do not edit by hand.
   Every file the app needs is stored on first visit, so it opens and plays with no signal. Network first (a new version is picked up straight away), the stored copy as the fallback. */
const CACHE = 'glassgroove-v0.2.0';
const FILES = [
  "./", "css/style.css", "css/takes.css", "examples/demo.sqz", "icons/icon-192.png", "icons/icon-512.png", "icons/icon-maskable-512.png", "index.html", "manifest.webmanifest", "src/app.js", "src/config.js", "src/dev/devtools.js", "src/engine/audio.js", "src/engine/clock.js", "src/engine/kits.js", "src/engine/loopfile.js", "src/engine/seq.js", "src/engine/styles.js", "src/events.js", "src/main.js", "src/perf/format.js", "src/perf/playback.js", "src/rec/library.js", "src/rec/recorder.js", "src/rec/wav.js", "src/rec/zip.js", "src/share.js", "src/takes/app.js", "src/takes/edit.js", "src/takes/main.js", "src/takes/render.js", "src/takes/timeline.js", "src/takes/video.js", "src/ui/beat.js", "src/ui/dom.js", "src/ui/extras.js", "src/ui/feedback.js", "src/ui/keep.js", "src/ui/look.js", "src/ui/nav.js", "src/ui/perform.js", "src/ui/play.js", "src/ui/settings.js", "src/ui/sheets.js", "src/ui/sound.js", "src/ui/surface.js", "src/ui/surge.js", "src/util.js", "src/visual/engine.js", "src/visual/press.js", "src/visual/scenes.js", "takes.html", "vendor/lame.min.js"
];
self.addEventListener('install', (e) => { self.skipWaiting(); e.waitUntil(caches.open(CACHE).then((c) => Promise.all(FILES.map((f) => c.add(f).catch(() => {}))))); });
self.addEventListener('activate', (e) => { e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', (e) => {
  const r = e.request;
  if (r.method !== 'GET' || new URL(r.url).origin !== location.origin) return;
  e.respondWith(fetch(r).then((res) => { if (res.ok) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(r, copy)); } return res; })
    .catch(() => caches.match(r, { ignoreSearch: true }).then((hit) => hit || (r.mode === 'navigate' ? caches.match('index.html') : Response.error()))));
});
