/* Writes sw.js: the service worker with the list of every file the app needs, so the whole thing (both pages, every module, the MP3 encoder, the icons) works with no signal.
   Run it before a release:  node tools/build-sw.js   (npm run sw) */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const version = /version: '([^']+)'/.exec(fs.readFileSync(path.join(root, 'src/config.js'), 'utf8'))[1];
const walk = (d) => fs.readdirSync(path.join(root, d), { withFileTypes: true }).flatMap((e) => (e.isDirectory() ? walk(`${d}/${e.name}`) : [`${d}/${e.name}`]));
const files = ['./', 'index.html', 'takes.html', 'manifest.webmanifest', ...['css', 'src', 'icons', 'vendor', 'examples'].flatMap(walk).filter((f) => !/README|LICENSE/i.test(f))].sort();
const out = `/* Glass Groove: the service worker. Generated by tools/build-sw.js: do not edit by hand.
   Every file the app needs is stored on first visit, so it opens and plays with no signal. Network first (a new version is picked up straight away), the stored copy as the fallback. */
const CACHE = 'glassgroove-v${version}';
const FILES = ${JSON.stringify(files, null, 1).replace(/\n\s*/g, ' ').replace('[ ', '[\n  ').replace(/ \]$/, '\n]')};
self.addEventListener('install', (e) => { self.skipWaiting(); e.waitUntil(caches.open(CACHE).then((c) => Promise.all(FILES.map((f) => c.add(f))))); });
self.addEventListener('activate', (e) => { e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', (e) => {
  const r = e.request;
  if (r.method !== 'GET' || new URL(r.url).origin !== location.origin) return;
  e.respondWith(fetch(r).then((res) => { if (res.ok) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(r, copy)); } return res; })
    .catch(() => caches.match(r, { ignoreSearch: true }).then((hit) => hit || (r.mode === 'navigate' ? caches.match('index.html') : Response.error()))));
});
`;
fs.writeFileSync(path.join(root, 'sw.js'), out);
console.log(`sw.js: ${files.length} files, cache glassgroove-v${version}`);
